print("Welcome to the Band Name Generator!")
print("Are you ready to rock?")
city = input("What city did you grow up in?\n")
pet_name = input("What is the name of your pet?\n")
print("Your band name could be " + city + " " + pet_name)
